name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      
      - name: actions-setup-mysql
        uses: shogo82148/actions-setup-mysql@v1.33.0    
        with:
          mysql-version: "5.7"
      
      - name : create northwind
        run: mysql -uroot -e "create database northwind;"
      
      - name: copy db
        run: mysql -uroot --default-character-set=utf8 northwind < sql/mysql/northwind.sql

      - name: Install npm dependencies
        run: npm install yarn -g && yarn install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Run tests
        run: npm run test

      - name: Run coveralls
        run: npm run coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
