name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with: 
          mysql version: "5.7"
          mysql root password: 123456 # Required if "mysql user" is empty, default is empty. The root superuser password
      
      - name: start mysql
        run: sudo /etc/init.d/mysql start
      
      - name : create northwind
        run: mysql -h 127.0.0.1 -u root -p123456  -e "create database northwind;"
      
      - name: copy db
        run: mysql -h 127.0.0.1 -u root -p123456 --default-character-set=utf8 northwind < sql/mysql/northwind.sql

      - name: Install npm dependencies
        run: npm install yarn -g && yarn install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Run tests
        run: npm run test

      - name: Run coveralls
        run: npm run coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
